# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('novelname', models.CharField(max_length=100)),
                ('novelimg', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novel',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='novelid',
            field=models.ForeignKey(db_column='novelid', on_delete=django.db.models.deletion.DO_NOTHING, to='test_postgresql.Novel'),
        ),
    ]
