# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
